version: '3'

x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  image: custom-airflow:2.7.1-python3.9
  env_file:
    - airflow.env
  volumes:
    - ./docker-data/config:/opt/airflow/config
    - ./dags:/opt/airflow/dags
    - ./docker-data/data:/opt/airflow/data
    - ./docker-data/etls:/opt/airflow/etls
    - ./docker-data/logs:/opt/airflow/logs
    - ./docker-data/pipelines:/opt/airflow/pipelines
    - ./data_collector:/opt/airflow/data_collector
    # - ./commons:/opt/airflow/commons
    - ./data-loading:/opt/airflow/data-loading
    - ./static_vars:/opt/airflow/static_vars
    - ./s3_utils:/opt/airflow/s3_utils
    - ./dbmodel:/opt/airflow/dbmodel
    - ./docs:/opt/airflow/docs
    - ./transforms:/opt/airflow/transforms
    - ./data_utils:/opt/airflow/data_utils
    - ./docker-data/plugins:/opt/airflow/plugins
    - ./docker-data/tests:/opt/airflow/tests
    - ./docker-data/utils:/opt/airflow/utils
   # - ./airflow.cfg:/opt/airflow/airflow.cfg
    - ./requirements.txt:/opt/airflow/requirements.txt
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - "6379:6379"

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "pip install -r /opt/airflow/requirements.txt && airflow db init && airflow db upgrade && airflow users create --username admin --firstname admin --lastname admin --role Admin --email airflow@airflow.com --password admin"
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-worker:
    <<: *airflow-common
    command: celery worker

  # chrome:
  #       image: selenium-chrome
  #       build:
  #         context: .
  #         dockerfile: Dockerfile.chrome
  #       hostname: chrome
  #       privileged: true
  #       shm_size: 2g
  #       ports:
  #          - "4444:4444"
  
  firefox:
        image: selenium-firefox
        build:
          context: .
          dockerfile: Dockerfile.firefox
        hostname: firefox
        shm_size: 2g
        privileged: true
        ports:
          - "4444:4444"